/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.5
 * Generated at: 2018-05-10 09:39:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gosichonProc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".box{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\twidth:340px;\r\n");
      out.write("\tmargin:5px;\r\n");
      out.write("}\r\n");
      out.write("img{\r\n");
      out.write("\twidth:340px;\r\n");
      out.write("\theight:300px;\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("\t list-style: none;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("span{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding-left:7px;\r\n");
      out.write("}\r\n");
      out.write("#name{\r\n");
      out.write("\tfont-size: 17px;\r\n");
      out.write("    line-height: 19px;\r\n");
      out.write("    font-weight: 900;\r\n");
      out.write("    color: #404040;\r\n");
      out.write("    margin-bottom: 3px;\r\n");
      out.write("}\r\n");
      out.write("#explain{\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    line-height: 13px;\r\n");
      out.write("    color: #757575;\r\n");
      out.write("}\r\n");
      out.write("#time{\r\n");
      out.write("\tmargin-top:5px;\r\n");
      out.write("\tline-height: 19px;\r\n");
      out.write("    font-weight: 900;\r\n");
      out.write("    color:#ff9933;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"dabuzzi.jsp\">\r\n");
      out.write("\t\t<img src=\"image/dabuzzi_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">다부찌</span>\r\n");
      out.write("\t\t<span id=\"explain\">얼큰한 부대찌개와 바삭한 감자튀김의 조화</span>\r\n");
      out.write("\t\t<span id=\"time\">10분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"sam.jsp\">\r\n");
      out.write("\t\t<img src=\"image/sam_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">삼동이</span>\r\n");
      out.write("\t\t<span id=\"explain\">퓨전 삼겹살 덮밥</span>\r\n");
      out.write("\t\t<span id=\"time\">13분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"hong.jsp\">\r\n");
      out.write("\t\t<img src=\"image/hong_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">홍오로</span>\r\n");
      out.write("\t\t<span id=\"explain\">불맛 가득 퓨전 중화 음식</span>\r\n");
      out.write("\t\t<span id=\"time\">10분</span>\r\n");
      out.write("\t\t</a>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"sambong.jsp\">\r\n");
      out.write("\t\t<img src=\"image/sambong_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">삼봉</span>\r\n");
      out.write("\t\t<span id=\"explain\">밥이 무한리필인 김치찌개 메뉴가 대표</span>\r\n");
      out.write("\t\t<span id=\"time\">11분</span>\r\n");
      out.write("\t\t</a>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"dduck.jsp\">\r\n");
      out.write("\t\t<img src=\"image/dduck_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">빨강떡볶이</span>\r\n");
      out.write("\t\t<span id=\"explain\">매운맛 단계가 있는 저렴한 떡볶이</span>\r\n");
      out.write("\t\t<span id=\"time\">11분</span>\r\n");
      out.write("\t\t</a>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"hot.jsp\">\r\n");
      out.write("\t\t<img src=\"image/hot_f2.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">엽기떡볶이</span>\r\n");
      out.write("\t\t<span id=\"explain\">대한민국 대표 매운 떡볶이</span>\r\n");
      out.write("\t\t<span id=\"time\">15분</span>\r\n");
      out.write("\t\t</a>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"mom.jsp\">\r\n");
      out.write("\t\t<img src=\"image/mom_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">큰엄마네떡볶이아울렛</span>\r\n");
      out.write("\t\t<span id=\"explain\">넓은 인원 회식 가능한 떡볶이집</span>\r\n");
      out.write("\t\t<span id=\"time\">2분</span>\r\n");
      out.write("\t\t</a>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"mirim.jsp\">\r\n");
      out.write("\t\t<img src=\"image/mirim_f.JPG\">\r\n");
      out.write("\t\t<span id=\"name\">미림분식</span>\r\n");
      out.write("\t\t<span id=\"explain\">이름부터 미림인 즉석떡볶이집</span>\r\n");
      out.write("\t\t<span id=\"time\">2분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"pork.jsp\">\r\n");
      out.write("\t\t<img src=\"image/pork_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">이쁜돼지고기</span>\r\n");
      out.write("\t\t<span id=\"explain\">삼겹살과 목살 무한리필</span>\r\n");
      out.write("\t\t<span id=\"time\">14분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"chiken.jsp\">\r\n");
      out.write("\t\t<img src=\"image/chiken_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">맛닭꼬</span>\r\n");
      out.write("\t\t<span id=\"explain\">오븐에 구운 담백한 치킨</span>\r\n");
      out.write("\t\t<span id=\"time\">11분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"amasvin.jsp\">\r\n");
      out.write("\t\t<img src=\"image/amasvin_f2.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">아마스빈</span>\r\n");
      out.write("\t\t<span id=\"explain\">달콤 쫀득 버블티, 타피오카펄로 든든한 간식</span>\r\n");
      out.write("\t\t<span id=\"time\">7분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"waffle.jsp\">\r\n");
      out.write("\t\t<img src=\"image/waffle_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">바바플</span>\r\n");
      out.write("\t\t<span id=\"explain\">저렴한 가격으로 맛보는 수제 와플</span>\r\n");
      out.write("\t\t<span id=\"time\">11분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"bananau.jsp\">\r\n");
      out.write("\t\t<img src=\"image/bananau_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">바나나유</span>\r\n");
      out.write("\t\t<span id=\"explain\">떠오르는 신흥강자! 생바나나 음료</span>\r\n");
      out.write("\t\t<span id=\"time\">9분</span>\r\n");
      out.write("\t\t</a>\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"gggo.jsp\">\r\n");
      out.write("\t\t<img src=\"image/gigigo_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">지지고</span>\r\n");
      out.write("\t\t<span id=\"explain\">일본식 볶음 컵요리</span>\r\n");
      out.write("\t\t<span id=\"time\">10분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"alchon.jsp\">\r\n");
      out.write("\t\t<img src=\"image/alchon_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">알촌</span>\r\n");
      out.write("\t\t<span id=\"explain\">맛과 가격 모두 잡은 알밥</span>\r\n");
      out.write("\t\t<span id=\"time\">11분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"duckbong.jsp\">\r\n");
      out.write("\t\t<img src=\"image/duckbong_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">덕봉식당</span>\r\n");
      out.write("\t\t<span id=\"explain\">주문 즉시 조리하는 뜨끈한 집밥 음식</span>\r\n");
      out.write("\t\t<span id=\"time\">9분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"sin.jsp\">\r\n");
      out.write("\t\t<img src=\"image/sin_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">신전떡볶이</span>\r\n");
      out.write("\t\t<span id=\"explain\">매콤한 국물 떡볶이</span>\r\n");
      out.write("\t\t<span id=\"time\">14분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"box\">\r\n");
      out.write("\t\t<a href=\"kim.jsp\">\r\n");
      out.write("\t\t<img src=\"image/kim_f.jpg\">\r\n");
      out.write("\t\t<span id=\"name\">김밥천국</span>\r\n");
      out.write("\t\t<span id=\"explain\">번외) 저녁으로 최고인 만능 식당</span>\r\n");
      out.write("\t\t<span id=\"time\">2분</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t\r\n");
      out.write("</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
